import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faUpload,
  faFilePdf,
  faFileImage,
  faList,
  faGrip,
  faMoon,
  faSun,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faDownload,
  faCheck,
  faXmark,
  faArrowRight,
  faArrowLeft,
  faMagnifyingGlass,
  faTrash,
  faEye,
  faSpinner,
  faWandMagicSparkles,
  faFile,
  faFileCircleExclamation,
  faChevronDown,
  faChevronUp,
  faCircleExclamation,
  faTriangleExclamation,
  faCircleCheck,
  faLink,
  faLinkSlash,
  faPlus,
  faTable,
  faArrowUpFromBracket,
  faBan,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faUpload,
  faFilePdf,
  faFileImage,
  faList,
  faGrip,
  faMoon,
  faSun,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faDownload,
  faCheck,
  faXmark,
  faArrowRight,
  faArrowLeft,
  faMagnifyingGlass,
  faTrash,
  faEye,
  faSpinner,
  faWandMagicSparkles,
  faFile,
  faFileCircleExclamation,
  faChevronDown,
  faChevronUp,
  faCircleExclamation,
  faTriangleExclamation,
  faCircleCheck,
  faLink,
  faLinkSlash,
  faPlus,
  faTable,
  faArrowUpFromBracket,
  faBan,
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('FontAwesomeIcon', FontAwesomeIcon)
})
